---
- name: Get vm info
  community.vmware.vmware_vm_info:
    hostname: "{{ web_url }}"
    password: "{{ web_userpass }}"
    username: "{{ web_username }}"
    # show_tag: true
    validate_certs: no
  delegate_to: localhost
  register: search_results

- name: Print a search results
  ansible.builtin.debug:
    msg: "{{ search_results }}"
