---
- name: Request Deployment in vRealize Automation
  hosts: all
  gather_facts: no

  vars:
    vra_catalogItem: "Windows Server"   # Replace with your Aria/vRA catalog item name
    vmname: "winsrv01"                  # Replace with your desired VM name
    os_image: "Windows Server 2022"     # Windows Server 2016, 2019 or 2022
    hardware_config: "Small"            # Small, Medium or Large
    address: "10.10.10.10"              # Replace with IPv4 address

  tasks:
    - name: Aria Stuff
      block:
        - name: Include role task for aria auth
          ansible.builtin.include_role:
            name: ans_vmware_aria_role
            tasks_from: "auth/auth_getToken.yml"

        - name: Include role task for aria catalog item info
          ansible.builtin.include_role:
            name: ans_vmware_aria_role
            tasks_from: "catalog/catalogItem_getInfo.yml"
          vars:
            catalog_item: "{{ vra_catalogItem }}"

        - name: Include role task for aria catalog item request
          ansible.builtin.include_role:
            name: ans_vmware_aria_role
            tasks_from: "catalog/catalogItem_request.yml"
          vars:
            vmname: "{{ input_vmname }}"
            os_image: "{{ input_os_image}}"
            hardware_config: "{{ input_hardware_config }}"
            address: "{{ input_address }}"
